### ISSUE TITLE
我可以在我的模拟系统里使用这些代码吗？

### ISSUE THREAD

**Issue by timegzs** [duoduo666/jisuanba_pygame_jisuanji#6]
https://gitee.com/timefiles/timephone-guisim

**Comment by timegzs** [comment]
我自己做吧

**Comment by duoduo666** [comment]
没问题没问题

**Comment by timegzs** [comment]
额，我自己做了一个，不用了



在 2021-02-19 14:58:28，"隋顺意" ***@***.***> 写道：

没问题没问题
